
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 1
  host: localhost
  port: 5432

development:
  <<: *default
  database: postgres
  password: 1

test:
  <<: *default
  database: postgres
  password: 1

production:
  <<: *default
  database: postgres
  username: postgres
  password: 1
